media:
  - name: uploads
    label: Uploads
    input: public/uploads
    output: /uploads

components:
  pricing:
    label: Pricing
    type: object
    fields:
      - name: type
        label: Pricing Type
        type: select
        required: true
        options:
          values:
            - label: Single price
              value: single
            - label: By size
              value: by_size

      - name: currency
        label: Currency
        type: select
        required: true
        options:
          values:
            - label: USD
              value: USD
            - label: LBP
              value: LBP

      - name: price
        label: Price (single)
        type: number
        required: false

      - name: sizes
        label: Sizes (by size)
        type: object
        list: true
        required: false
        fields:
          - name: label
            label: Size label (e.g. 6", Small, 10 persons)
            type: string
            required: true
          - name: price
            label: Price
            type: number
            required: true

  seasonalWindow:
    label: Seasonal Window
    type: object
    fields:
      - name: start
        label: Start (MM-DD)
        type: string
        required: false
        description: "Example: 05-01"
      - name: end
        label: End (MM-DD)
        type: string
        required: false
        description: "Example: 08-31"

content:
  # =========================
  # CAKES (taxonomy + items)
  # =========================
  - name: cakeSections
    label: Cake Sections
    type: collection
    path: content/cakeSections
    filename: "{primary}.md"
    view:
      primary: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: order
        label: Order
        type: number
        required: true
      - name: description
        label: Description
        type: text
        required: false

  - name: cakeBadges
    label: Cake Badges
    type: collection
    path: content/cakeBadges
    filename: "{primary}.md"
    view:
      primary: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: short
        label: Short label (optional)
        type: string
        required: false

  - name: cakes
    label: Cakes
    type: collection
    path: content/cakes
    filename: "{primary}.md"
    view:
      primary: name
    fields:
      - name: name
        label: Cake Name
        type: string
        required: true

      - name: image
        label: Image
        type: image
        required: true

      - name: section
        label: Menu Section
        type: reference
        required: true
        options:
          collection: cakeSections
          search: title
          value: "{name}"
          label: "{title}"

      - name: badges
        label: Badges (pills)
        type: reference
        required: false
        options:
          collection: cakeBadges
          multiple: true
          search: title
          value: "{name}"
          label: "{title}"

      - name: flavors
        label: Flavors (chips like strawberry, lemon)
        type: string
        list: true
        required: false

      - name: description
        label: Short Description
        type: text
        required: false

      - name: pricing
        component: pricing
        required: true

      - name: seasonal
        component: seasonalWindow
        required: false
        description: Only fill this if the cake should gray-out when out of season.

# =========================
# Catering — Sections
# =========================
- name: cateringSections
  label: Catering — Sections
  type: collection
  path: content/cateringSections
  filename: "{primary}.md"
  view:
    primary: title
  fields:
    - name: title
      label: Title
      type: string
      required: true

    - name: order
      label: Order
      type: number
      default: 999

    - name: description
      label: Short description (optional)
      type: string

# =========================
# Catering — Signature Items
# =========================
- name: cateringItems
  label: Catering — Signature Items
  type: collection
  path: content/cateringItems
  filename: "{primary}.md"
  view:
    primary: name
  fields:
    - name: isActive
      label: Active
      type: boolean
      default: true

    - name: name
      label: Name
      type: string
      required: true

    - name: sectionRef
      label: Section
      type: reference
      required: true
      options:
        collection: cateringSections
        search: title
        value: "{name}"
        label: "{title}"

    - name: image
      label: Image
      type: image
      description: "Uploads to /public/uploads and saves as /uploads/..."

    - name: priceLabel
      label: Price label (optional)
      type: string
      description: 'Examples: "LBP 450,000", "$12", "From $10", or leave empty'

    - name: order
      label: Order
      type: number
      default: 999

    - name: body
      label: Description
      type: rich-text

# =========================
# Catering — Plat du Jour (Weekly)
# One document per week with a 7-day list
# =========================
- name: platDuJourWeeks
  label: Catering — Plat du Jour (Weeks)
  type: collection
  path: content/platDuJourWeeks
  filename: "{primary}.md"
  view:
    primary: weekStart
  fields:
    - name: isActive
      label: Active
      type: boolean
      default: true

    - name: weekStart
      label: Week Start (Monday)
      type: date
      required: true
      description: "Pick the Monday of the week. Past days will auto-gray on the page."

    - name: note
      label: Note (optional)
      type: string
      description: 'Example: "Orders close at 6PM."'

    - name: days
      label: Week Menu (7 days)
      type: list
      required: true
      description: "Add 7 entries: Monday → Sunday"
      items:
        type: object
        fields:
          - name: day
            label: Day
            type: select
            required: true
            options:
              values:
                - label: Monday
                  value: Monday
                - label: Tuesday
                  value: Tuesday
                - label: Wednesday
                  value: Wednesday
                - label: Thursday
                  value: Thursday
                - label: Friday
                  value: Friday
                - label: Saturday
                  value: Saturday
                - label: Sunday
                  value: Sunday

          - name: isSet
            label: Menu set for this day
            type: boolean
            default: true

          - name: name
            label: Dish name
            type: string

          - name: description
            label: Short description
            type: string

          - name: image
            label: Image
            type: image

          - name: priceLabel
            label: Price label (optional)
            type: string
